# Generated by Django 2.2.6 on 2020-05-29 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
    ]
